version: "3.9"

services:
  api:
    build: .
    image: medimaging-ai/api:latest
    env_file:
      - .env
    environment:
      MODEL_CHECKPOINT_DIR: /checkpoints
    volumes:
      - checkpoints:/checkpoints
    expose:
      - "8000"
    restart: unless-stopped

  proxy:
    image: nginx:1.25-alpine
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    restart: unless-stopped

volumes:
  checkpoints:

